services:
  caddy:
    image: caddy:2.11.4
    restart: unless-stopped

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

    networks:
      - edge

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

volumes:
  caddy-data:
  caddy-config:

networks:
  edge:
    external: true
